name: Regression Tests

on:
  workflow_dispatch:
    inputs:
      marker:
        description: 'Test scenario tags'
        required: false
        type: string
        default: ''
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        default: "dev"
      product:
        description: 'The product we are testing'
        type: choice
        options:
          - RAVS
        required: false
        default: RAVS
      id:
        description: 'Unique run identifier (Do not change this)'
        required: false
        default: "Manually Triggered Run"
      pull_request_id:
        description: 'The ID of the pull request. This should be in the format pr-xxxx where xxxx is the pull request id'
        required: false
        default: ""
      github_tag:
        description: 'The GitHub tag to run the test pack from'
        required: false
        default: "main"
  push:
    branches:
      - '**'
  schedule:
    - cron: '0 6 * * *'
    - cron: '30 6 * * *'

jobs:
  regression_tests:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'push' && 'dev' || (github.event_name == 'schedule' && github.event.schedule == '0 6 * * *' && 'qa' || (github.event_name == 'workflow_dispatch' && inputs.environment || 'dev')) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest-playwright  # Ensure latest pytest-playwright
          pip install --upgrade -r requirements.txt

      - name: Verify Playwright & Pytest Installation
        run: |
          python -m pip list | grep playwright
          python -m pip list | grep pytest

      - name: Install Playwright (Latest)
        run: |
          python -m pip install --no-cache-dir --upgrade playwright
          npx playwright install --with-deps

      - name: Enable Additional Repositories
        run: |
          sudo add-apt-repository universe
          sudo add-apt-repository multiverse
          sudo apt-get update

      - name: Install Required System Libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends --fix-missing \
            libgtk-4-1 libgraphene-1.0-0 libwoff2-dev libvpx-dev libevent-2.1-7 \
            libopus0 libgstreamer-plugins-base1.0-0 libgstreamer1.0-0 \
            libavif-dev libharfbuzz-icu0 libsecret-1-0 libhyphen0 libmanette-0.2-0 \
            libgles2 libx264-164 || true

      - name: Install Allure Commandline
        run: |
          curl -o allure-commandline-2.17.3.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.17.3/allure-commandline-2.17.3.tgz && \
          tar -zxvf allure-commandline-2.17.3.tgz -C /opt/ && \
          sudo ln -s /opt/allure-2.17.3/bin/allure /usr/bin/allure && \
          rm -rf allure-commandline-2.17.3.tgz

      - name: Verify Allure Installation
        run: allure --version

      - name: Run Tests
        env:
          TZ: "Europe/London"
          LANG: "en_GB.UTF-8"
          LANGUAGE: "en_GB:en"
          LC_ALL: "en_GB.UTF-8"
          TEST_ENVIRONMENT: ${{ env.ENV }}
          RAVS_PASSWORD: ${{ secrets.RAVS_PASSWORD }}
          HEADLESS_MODE: "true"
          BROWSER: "edge"
          MARKER: "login"
          AGENTS: 3
        run: |
          tox -v
        continue-on-error: true

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: error

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.EPS_REGRESSION_TESTING_APP_ID }}
          private-key: ${{ secrets.EPS_REGRESSION_TESTING_PEM }}
          owner: "NHSDigital"
          repositories: "ravs-tests,ravs-test-reports"

      - name: Trigger test report generation
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            -d '{"ref": "main", "inputs": {"run_id": "${{ github.run_id }}"}}' \
            "https://api.github.com/repos/NHSDigital/ravs-test-reports/actions/workflows/publish_report.yml/dispatches"
